
import Footer from "./Common/Footer";
import Header from "./Common/Header";
import "@/app/globals.css";




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header/>
        {children}
      
        <Footer/>
      </body>
    </html>
  );
}
